---
- hosts: localhost
  become: yes

  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: ssh, tags: ['ssh'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: media-pool, tags: ['media-pool'] }

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"