---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Create OpenSSH systemd unit file directory
  file: path=/etc/systemd/system/sshd.socket.d state=directory

- name: Push OpenSSH socket unit file
  template: src=sshd-socket-override.conf.j2 dest=/etc/systemd/system/sshd.socket.d/override.conf
  notify:
    - reload systemd config
    - restart sshd

- name: Generate /etc/ssh/ RSA host key
  command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
  creates: /etc/ssh/ssh_host_rsa_key

- name: Generate /etc/ssh/ DSA host key
  command : ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -C "" -N ""
  creates: /etc/ssh/ssh_host_dsa_key

- name: Generate /etc/ssh/ ECDSA host key
  command : ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -C "" -N ""
  creates: /etc/ssh/ssh_host_ecdsa_key

- name: Enable and start OpenSSH
  service: name=sshd.socket enabled=yes state=started
  when: ssh.enable_sshd == True

- name: Disable and stop OpenSSH
  service: name=sshd.socket enabled=no state=stopped
  when: ssh.enable_sshd == False

- name: Make directory for user SSH key
  file: path=/home/{{ user.name }}/.ssh state=directory owner={{ user.name }} group={{ user.group }}