---
- name: Install nfs client
  pacman: 
    name: nfs-utils
    state: present

- name: Mount MediaPool nfs share
  mount:
    name: "{{mediapool.mount}}"
    src: "{{mediapool.server}}:{{mediapool.path}}"
    fstype: nfs
    state: mounted
  tags:
    - media-pool