---
- name: Install plex-media-server
  aur: 
    name: "{{ plex_media_server.package }}"
    user: "{{ user.name }}"
    skip_pgp: yes

- name: Enable and start Plex
  service: 
    name: plexmediaserver.service
    enabled: yes
    state: started
  when: plex_media_server.enable == True

- name: Increase inotify limit for users
  copy:
      dest: "/etc/sysctl.d/40-max-user-watches.conf"
      content: |
        fs.inotify.max_user_watches=524288

- name: Add Packman hook to restart PMS after an update
  template: src=pms-update-post.hook.j2 dest=/etc/pacman.d/hooks/pms-update-post.hook

- name: Create a cron to automatically update pms
  cron:
    name: PMS autoupdate
    minute: 0
    hour: 8
    user: "{{ user.name }}"
    job: "timeout -s 2 300 yay --nocleanmenu --nodiffmenu -Syy plex-media-server-plexpass"
    cron_file: ansible_pms-autoupdate